name: ChestStacker
version: '${project.version}'  # Grabs from pom—auto-sync magic!
main: com.excrele.cheststacker.ChestStackerPlugin  # Points to our main class—like a signpost.
author: Excrele  # Dev cred—holla!
description: Stack up to 1000 items in chests & barrels for epic storage! Player inv stays vanilla.
api-version: '1.21'  # Matches your Paper server—smooth sailing!

# Perms: Who gets the power? Everyone for now—easy mode.
permissions:
  cheststacker.use:
    description: Unlocks mega-stacking in containers.
    default: true  # All players can stack—no hassle.

# No commands—keeps it simple. Later: /stacker reload for config changes.